spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.01:3306/deneng_space?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 20030322
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 172800
server:
  port: 8079
Filter:
  loginFilterEnable: true
JWT:
  key: nihao